## NUMPY

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# get array dimensions
print(b.ndim)

2


In [5]:
# get array shape
print(b.shape)

(2, 3)


In [6]:
# get type
print(b.dtype)

int64


In [7]:
c = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(c)

[[1. 2. 3.]
 [3. 4. 5.]]


In [8]:
# [row, column]
print(c[0, 1])

2.0


In [9]:
# specific row
print(c[0, :])

[1. 2. 3.]


In [10]:
# specific column
print(c[:, 1])

[2. 4.]


In [11]:
# fancy
print(c[0, 1:2:1])

[2.]


In [12]:
c[0,0] = 10.
c

array([[10.,  2.,  3.],
       [ 3.,  4.,  5.]])

In [13]:
array_a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
print(array_a)
array_a[:, 2] = 20
print(array_a)
array_a[:, 2] = [1, 2, 3]
print(array_a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2 20  4  5]
 [ 6  7 20  9 10]
 [11 12 20 14 15]]
[[ 1  2  1  4  5]
 [ 6  7  2  9 10]
 [11 12  3 14 15]]


In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((3,3), .1)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [19]:
np.full_like(a, 1)

array([1, 1, 1])

In [20]:
np.random.rand(4,2)

array([[0.74968368, 0.40924961],
       [0.77354708, 0.63890281],
       [0.92678643, 0.8148866 ],
       [0.51526922, 0.91226394]])

In [26]:
np.random.randint(0, 10, size=(3,3))

array([[6, 6, 7],
       [4, 6, 7],
       [6, 9, 6]])

In [32]:
output = np.zeros((7,7))
z = np.ones((5,5))
z[2,2] = 5
output[1:-1, 1:-1] = z
output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### Copying arrays

In [33]:
x = z.copy()
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 5., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Math

In [34]:
a = np.random.randint(0,10, size=(3,3))
a

array([[3, 7, 0],
       [7, 5, 2],
       [1, 7, 7]])

In [36]:
a * 2

array([[ 6, 14,  0],
       [14, 10,  4],
       [ 2, 14, 14]])

In [37]:
b = np.random.randint(10,20, size=(3,3))
b

array([[19, 11, 12],
       [13, 13, 13],
       [15, 14, 17]])

In [38]:
a + b

array([[22, 18, 12],
       [20, 18, 15],
       [16, 21, 24]])

In [39]:
b // a

array([[ 6,  1,  0],
       [ 1,  2,  6],
       [15,  2,  2]])